[package]
name = "bsp"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.6.0"
winit = "0.25"
env_logger = "0.9"
rand = "0.8"
cgmath = "0.18.0"